// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/color-palettes/Earth.tsx": () => import("../components/mockups/color-palettes/Earth.tsx"),
  "./components/mockups/color-palettes/Fire.tsx": () => import("../components/mockups/color-palettes/Fire.tsx"),
  "./components/mockups/color-palettes/Water.tsx": () => import("../components/mockups/color-palettes/Water.tsx")
};
